#!/bin/bash
# Installation script for VOLUTE launchers (macOS/Linux)
# Generates Unix launcher scripts for different model configurations

set -e

echo "======================================================================"
echo "VOLUTE Launchers Installation (macOS/Linux)"
echo "======================================================================"
echo ""

# Detect OS for specific features
OS="linux"
if [[ "$OSTYPE" == "darwin"* ]]; then
    OS="macos"
fi

echo "Detected OS: $OS"
echo ""

# Check we're in SAM2 directory
if [ ! -d "tools" ] || [ ! -d "sam2" ]; then
    echo "Error: This script must be run from the root of your SAM2 installation"
    exit 1
fi

# Create launchers directory
LAUNCHERS_DIR="tools/launchers"
mkdir -p "$LAUNCHERS_DIR"
echo "Created directory: $LAUNCHERS_DIR"
echo ""

# Function to create Unix launcher
create_unix_launcher() {
    local name=$1
    local description=$2
    local args=$3
    local file="$LAUNCHERS_DIR/${name}.sh"

    cat > "$file" << 'EOF'
#!/bin/bash
# DESCRIPTION_PLACEHOLDER
cd "$(dirname "$0")/../.."
python tools/VOLUTE.py ARGS_PLACEHOLDER "$@"
EOF

    sed -i.bak "s|DESCRIPTION_PLACEHOLDER|${description}|g" "$file"
    sed -i.bak "s|ARGS_PLACEHOLDER|${args}|g" "$file"
    rm "${file}.bak" 2>/dev/null || true

    chmod +x "$file"
    echo "  ✓ Created: ${name}.sh"
}

# Generate Unix launchers
echo "Generating launcher scripts..."
echo ""

create_unix_launcher "volute"        "VOLUTE — asks which model to use" ""
create_unix_launcher "sam2_default"    "SAM2 default model (Hiera Large)" "--model sam2"
create_unix_launcher "sam2_small"      "SAM2 small model (faster)" "--config configs/sam2.1/sam2.1_hiera_s.yaml --checkpoint checkpoints/sam2.1_hiera_small.pt"
create_unix_launcher "medsam2_general" "MedSAM2 general medical model" "--model medsam2"
create_unix_launcher "medsam2_ct"      "MedSAM2 CT lesion model" "--checkpoint checkpoints/MedSAM2_CTLesion.pt --config configs/medsam2_configs/sam2.1_hiera_t512.yaml"
create_unix_launcher "medsam2_heart"   "MedSAM2 heart ultrasound model" "--checkpoint checkpoints/MedSAM2_US_Heart.pt --config configs/medsam2_configs/sam2.1_hiera_t512.yaml"
create_unix_launcher "medsam2_liver"   "MedSAM2 liver MRI model" "--checkpoint checkpoints/MedSAM2_MRI_LiverLesion.pt --config configs/medsam2_configs/sam2.1_hiera_t512.yaml"
create_unix_launcher "sam2plus_mask"   "SAM2++ mask segmentation mode" "--model sam2plus --task mask"
create_unix_launcher "sam2plus_point"  "SAM2++ point tracking mode" "--model sam2plus --task point"

echo ""

# Create README
cat > "$LAUNCHERS_DIR/README.md" << 'EOF'
# VOLUTE Quick Launch Scripts

Generated by `tools/install_launchers_Unix_MacOS.sh` — re-run it to refresh them.
Each script moves to the root of the installation before starting the GUI, which
is the one thing the application cannot do for itself.

## Available Launchers

- **volute.sh**: starts the application without naming a model, so it asks
  which one to use — or goes straight to the default model when that dialog has
  been turned off in the settings

Naming a model on the command line skips that dialog, which is what the
remaining launchers do:

### SAM2 Models
- **sam2_default.sh**: SAM2 default model (Hiera Large) - Best accuracy
- **sam2_small.sh**: SAM2 small model - Faster processing

### MedSAM2 Models
- **medsam2_general.sh**: MedSAM2 general medical imaging model
- **medsam2_ct.sh**: MedSAM2 specialized for CT lesion segmentation
- **medsam2_heart.sh**: MedSAM2 specialized for heart ultrasound
- **medsam2_liver.sh**: MedSAM2 specialized for liver MRI lesions

### SAM2++ Models
- **sam2plus_mask.sh**: SAM2++ mask segmentation mode (drop-in SAM2 replacement)
- **sam2plus_point.sh**: SAM2++ point tracking mode (tracks points across frames)

## Usage

```bash
cd /path/to/sam2/tools/launchers
./volute.sh              # choose the model in the application
./sam2plus_point.sh        # straight to SAM2++ point tracking

# With debug mode
./sam2plus_point.sh --debug
```

## Creating Aliases (Optional)

Add to your `~/.bashrc` or `~/.zshrc`:

```bash
alias sam2='cd /path/to/sam2/tools/launchers && ./volute.sh'
alias sam2-med='cd /path/to/sam2/tools/launchers && ./medsam2_general.sh'
alias sam2-track='cd /path/to/sam2/tools/launchers && ./sam2plus_point.sh'
```

## Troubleshooting

**Scripts not executable:**
```bash
chmod +x *.sh
```

**Python environment:**
Make sure the correct conda environment is activated before running a launcher.
SAM2++ requires its own environment (`sam2_plus`); see `INSTALL.md` for details.
EOF

echo "  ✓ Created: README.md"
echo ""

echo "======================================================================"
echo "Installation Complete!"
echo "======================================================================"
echo ""
echo "Launchers installed in: $LAUNCHERS_DIR"
echo ""
echo "Usage:"
echo "  cd tools/launchers"
echo "  ./volute.sh             # choose the model in the application"
echo "  ./sam2plus_point.sh --debug"
echo ""
echo "See README.md in launchers/ for complete documentation"
echo ""
