@echo off
REM Installation script for VOLUTE launchers (Windows)
REM Generates Windows launcher scripts for different model configurations

setlocal enabledelayedexpansion

echo ======================================================================
echo VOLUTE Launchers Installation (Windows)
echo ======================================================================
echo.

REM Check we're in SAM2 directory
if not exist "tools" (
    echo Error: This script must be run from the root of your SAM2 installation
    pause
    exit /b 1
)

if not exist "sam2" (
    echo Error: This script must be run from the root of your SAM2 installation
    pause
    exit /b 1
)

REM Create launchers directory
set "LAUNCHERS_DIR=tools\launchers"
if not exist "%LAUNCHERS_DIR%" mkdir "%LAUNCHERS_DIR%"
echo Created directory: %LAUNCHERS_DIR%
echo.

echo Generating launcher scripts...
echo.

REM Create volute.bat - no model named, so the application asks
echo @echo off> "%LAUNCHERS_DIR%\volute.bat"
echo REM VOLUTE - asks which model to use>> "%LAUNCHERS_DIR%\volute.bat"
echo cd /d "%%~dp0\..\..">> "%LAUNCHERS_DIR%\volute.bat"
echo python tools\VOLUTE.py %%*>> "%LAUNCHERS_DIR%\volute.bat"
echo   + Created: volute.bat

REM Create sam2_default.bat
echo @echo off> "%LAUNCHERS_DIR%\sam2_default.bat"
echo REM SAM2 default model (Hiera Large)>> "%LAUNCHERS_DIR%\sam2_default.bat"
echo cd /d "%%~dp0\..\..">> "%LAUNCHERS_DIR%\sam2_default.bat"
echo python tools\VOLUTE.py --model sam2 %%*>> "%LAUNCHERS_DIR%\sam2_default.bat"
echo   + Created: sam2_default.bat

REM Create sam2_small.bat
echo @echo off> "%LAUNCHERS_DIR%\sam2_small.bat"
echo REM SAM2 small model (faster)>> "%LAUNCHERS_DIR%\sam2_small.bat"
echo cd /d "%%~dp0\..\..">> "%LAUNCHERS_DIR%\sam2_small.bat"
echo python tools\VOLUTE.py --config configs\sam2.1\sam2.1_hiera_s.yaml --checkpoint checkpoints\sam2.1_hiera_small.pt %%*>> "%LAUNCHERS_DIR%\sam2_small.bat"
echo   + Created: sam2_small.bat

REM Create medsam2_general.bat
echo @echo off> "%LAUNCHERS_DIR%\medsam2_general.bat"
echo REM MedSAM2 general medical model>> "%LAUNCHERS_DIR%\medsam2_general.bat"
echo cd /d "%%~dp0\..\..">> "%LAUNCHERS_DIR%\medsam2_general.bat"
echo python tools\VOLUTE.py --model medsam2 %%*>> "%LAUNCHERS_DIR%\medsam2_general.bat"
echo   + Created: medsam2_general.bat

REM Create medsam2_ct.bat
echo @echo off> "%LAUNCHERS_DIR%\medsam2_ct.bat"
echo REM MedSAM2 CT lesion model>> "%LAUNCHERS_DIR%\medsam2_ct.bat"
echo cd /d "%%~dp0\..\..">> "%LAUNCHERS_DIR%\medsam2_ct.bat"
echo python tools\VOLUTE.py --checkpoint checkpoints\MedSAM2_CTLesion.pt --config configs\medsam2_configs\sam2.1_hiera_t512.yaml %%*>> "%LAUNCHERS_DIR%\medsam2_ct.bat"
echo   + Created: medsam2_ct.bat

REM Create medsam2_heart.bat
echo @echo off> "%LAUNCHERS_DIR%\medsam2_heart.bat"
echo REM MedSAM2 heart ultrasound model>> "%LAUNCHERS_DIR%\medsam2_heart.bat"
echo cd /d "%%~dp0\..\..">> "%LAUNCHERS_DIR%\medsam2_heart.bat"
echo python tools\VOLUTE.py --checkpoint checkpoints\MedSAM2_US_Heart.pt --config configs\medsam2_configs\sam2.1_hiera_t512.yaml %%*>> "%LAUNCHERS_DIR%\medsam2_heart.bat"
echo   + Created: medsam2_heart.bat

REM Create medsam2_liver.bat
echo @echo off> "%LAUNCHERS_DIR%\medsam2_liver.bat"
echo REM MedSAM2 liver MRI model>> "%LAUNCHERS_DIR%\medsam2_liver.bat"
echo cd /d "%%~dp0\..\..">> "%LAUNCHERS_DIR%\medsam2_liver.bat"
echo python tools\VOLUTE.py --checkpoint checkpoints\MedSAM2_MRI_LiverLesion.pt --config configs\medsam2_configs\sam2.1_hiera_t512.yaml %%*>> "%LAUNCHERS_DIR%\medsam2_liver.bat"
echo   + Created: medsam2_liver.bat

REM Create sam2plus_mask.bat
echo @echo off> "%LAUNCHERS_DIR%\sam2plus_mask.bat"
echo REM SAM2++ mask segmentation mode>> "%LAUNCHERS_DIR%\sam2plus_mask.bat"
echo cd /d "%%~dp0\..\..">> "%LAUNCHERS_DIR%\sam2plus_mask.bat"
echo python tools\VOLUTE.py --model sam2plus --task mask %%*>> "%LAUNCHERS_DIR%\sam2plus_mask.bat"
echo   + Created: sam2plus_mask.bat

REM Create sam2plus_point.bat
echo @echo off> "%LAUNCHERS_DIR%\sam2plus_point.bat"
echo REM SAM2++ point tracking mode>> "%LAUNCHERS_DIR%\sam2plus_point.bat"
echo cd /d "%%~dp0\..\..">> "%LAUNCHERS_DIR%\sam2plus_point.bat"
echo python tools\VOLUTE.py --model sam2plus --task point %%*>> "%LAUNCHERS_DIR%\sam2plus_point.bat"
echo   + Created: sam2plus_point.bat

echo.

REM Create README
(
echo # VOLUTE Quick Launch Scripts
echo.
echo Generated by `tools\install_launchers_windows.bat` - re-run it to refresh them.
echo Each script moves to the root of the installation before starting the GUI,
echo which is the one thing the application cannot do for itself.
echo.
echo ## Available Launchers
echo.
echo - **volute.bat**: starts the application without naming a model, so it asks
echo   which one to use - or goes straight to the default model when that dialog
echo   has been turned off in the settings
echo.
echo Naming a model on the command line skips that dialog, which is what the
echo remaining launchers do:
echo.
echo ### SAM2 Models
echo - **sam2_default.bat**: SAM2 default model ^(Hiera Large^) - Best accuracy
echo - **sam2_small.bat**: SAM2 small model - Faster processing
echo.
echo ### MedSAM2 Models
echo - **medsam2_general.bat**: MedSAM2 general medical imaging model
echo - **medsam2_ct.bat**: MedSAM2 specialized for CT lesion segmentation
echo - **medsam2_heart.bat**: MedSAM2 specialized for heart ultrasound
echo - **medsam2_liver.bat**: MedSAM2 specialized for liver MRI lesions
echo.
echo ### SAM2++ Models
echo - **sam2plus_mask.bat**: SAM2++ mask segmentation mode ^(drop-in SAM2 replacement^)
echo - **sam2plus_point.bat**: SAM2++ point tracking mode ^(tracks points across frames^)
echo.
echo ## Usage
echo.
echo ```batch
echo cd C:\path\to\sam2\tools\launchers
echo volute.bat
echo sam2plus_point.bat
echo.
echo REM With debug mode
echo sam2plus_point.bat --debug
echo ```
echo.
echo ## Troubleshooting
echo.
echo **Python not found:**
echo Make sure the correct conda environment is activated.
echo SAM2++ requires its own environment ^(sam2_plus^); see INSTALL.md for details.
) > "%LAUNCHERS_DIR%\README.md"
echo   + Created: README.md

echo.
echo ======================================================================
echo Installation Complete!
echo ======================================================================
echo.
echo Launchers installed in: %LAUNCHERS_DIR%
echo.
echo Usage:
echo   cd tools\launchers
echo   volute.bat           (choose the model in the application)
echo   sam2plus_point.bat --debug
echo.
echo See README.md in launchers\ for complete documentation
echo.
pause
